### ISSUE TITLE
missing service

### ISSUE THREAD

**Issue by nhatchu** [nhpatt/ScreensPushBubble#1]
Hi,

Trying this sample for a few days now with liferay instance, i follow the video and use the Api key on my server. I change the sender id in this source code with my own project number, but can't get the device to register to my liferay instance. Do you know if there is something more i could do to register my device to the gcm service?

**Comment by nhatchu** [comment]
Found it. I had to add the use permission in the android manifest 

	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="app.cloudstringers.permission.C2D_MESSAGE" />

**Comment by nhpatt** [comment]
I'm glad you found it, we'll check the docs for missing pieces.
